import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import { Manga } from '../components/models/models';


@Injectable({
  providedIn: 'root'
})
export class MangaService {
  private mangasMock: Manga[] = [
    {
      id: 1,
      titulo: 'CHAINSAW MAN',
      autor: 'TATSUKI FUJIMOTO',
      tipoPublicacion: 'Tomos con Sobrecubierta',
      sinopsis: 'Denji es un chico pobre capaz de hacer cualquier cosa por dinero, incluso cazar demonios con su perro demonio Pochita.',
      portadaUrl: '/chainsawman/01.jpg',
      generos: ['Acción', 'Sobrenatural', 'Shonen'],
      estado: 'RESERVA',
      tomos: [
        { numero: 'Volumen 1', imagenUrl: '/chainsawman/01.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 2', imagenUrl: '/chainsawman/02.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 3', imagenUrl: '/chainsawman/03.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 4', imagenUrl: '/chainsawman/04.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 5', imagenUrl: '/chainsawman/05.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 6', imagenUrl: '/chainsawman/06.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 7', imagenUrl: '/chainsawman/07.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 8', imagenUrl: '/chainsawman/08.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 9', imagenUrl: '/chainsawman/09.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 10', imagenUrl: '/chainsawman/10.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 11', imagenUrl: '/chainsawman/11.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 12', imagenUrl: '/chainsawman/12.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 13', imagenUrl: '/chainsawman/13.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 14', imagenUrl: '/chainsawman/14.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 14 - Especial', imagenUrl: '/chainsawman/14-especial.jpg', precio: 17.25, estado: 'RESERVA' },
        { numero: 'Volumen 15', imagenUrl: '/chainsawman/15.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 16', imagenUrl: '/chainsawman/16.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 17', imagenUrl: '/chainsawman/17.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 18', imagenUrl: '/chainsawman/18.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 19', imagenUrl: '/chainsawman/19.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 20', imagenUrl: '/chainsawman/20.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 21', imagenUrl: '/chainsawman/21.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 22', imagenUrl: '/chainsawman/22.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 23', imagenUrl: '/chainsawman/23.jpg', precio: 14.50, estado: 'RESERVA' }
      ]
    },
    {
      id: 2,
      titulo: 'FUMANDO ATRÁS DEL SÚPER CON VOS',
      autor: 'JINUSHI',
      tipoPublicacion: 'Tomos con Sobrecubierta. B6 e incluye páginas a color',
      sinopsis: 'Sasaki es un oficinista estresado cuyo único refugio diario es Yamada, la alegre cajera de su supermercado favorito. Un día, tras una jornada especialmente dura, Sasaki no la encuentra en su turno. Al salir desanimado a buscar un lugar para fumar, se topa con Tayama, una chica con estilo alternativo que lo invita a compartir un cigarrillo en la zona trasera del local. Lo que Sasaki no sabe es que Tayama y Yamada son la misma persona.',
      portadaUrl: '/fumando/01.jpg',
      generos: ['Comedia', 'Recuentos de la vida', 'Romance'],
      estado: 'RESERVA',
      tomos: [
        { numero: 'Volumen 1', imagenUrl: '/fumando/01.jpg', precio: 16.75, estado: 'PREVENTA' }, 
        { numero: 'Volumen 2', imagenUrl: '/fumando/02.jpg', precio: 16.75, estado: 'RESERVA' },
        { numero: 'Volumen 3', imagenUrl: '/fumando/03.jpg', precio: 16.75, estado: 'PREVENTA' }, 
        { numero: 'Volumen 4', imagenUrl: '/fumando/04.jpg', precio: 16.75, estado: 'RESERVA' },
        { numero: 'Volumen 5', imagenUrl: '/fumando/05.jpg', precio: 16.75, estado: 'PREVENTA' }, 
        { numero: 'Volumen 6', imagenUrl: '/fumando/06.jpg', precio: 16.75, estado: 'RESERVA' },
        { numero: 'Volumen 7', imagenUrl: '/fumando/07.jpg', precio: 16.75, estado: 'PREVENTA' }, 
        { numero: 'Volumen 8', imagenUrl: '/fumando/08.jpg', precio: 16.75, estado: 'RESERVA' }
      ]
    },
  {
    id: 3,
    titulo: 'BLUE LOCK',
    autor: 'MUNEYUKI KANESHIRO & YUSUKE NOMURA',
      tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Tras la eliminación de Japón en el Mundial de 2018, la unión de fútbol japonesa contrata a Jinpachi Ego para crear un programa que produzca al delantero egoísta definitivo capaz de guiar al país a la gloria.',
    portadaUrl: '/bluelock/01.jpg',
    generos: ['Deportes', 'Drama', 'Shonen'],
    estado: 'RESERVA',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/bluelock/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/bluelock/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/bluelock/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/bluelock/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/bluelock/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/bluelock/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/bluelock/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/bluelock/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/bluelock/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/bluelock/10.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/bluelock/11.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/bluelock/12.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/bluelock/13.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/bluelock/14.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/bluelock/15.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 16', imagenUrl: '/bluelock/16.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 17', imagenUrl: '/bluelock/17.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 18', imagenUrl: '/bluelock/18.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 19', imagenUrl: '/bluelock/19.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 20', imagenUrl: '/bluelock/20.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 21', imagenUrl: '/bluelock/21.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 22', imagenUrl: '/bluelock/22.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 23', imagenUrl: '/bluelock/23.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 24', imagenUrl: '/bluelock/24.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 25', imagenUrl: '/bluelock/25.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 26', imagenUrl: '/bluelock/26.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 27', imagenUrl: '/bluelock/27.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 28', imagenUrl: '/bluelock/28.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 29', imagenUrl: '/bluelock/29.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 30', imagenUrl: '/bluelock/30.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 31', imagenUrl: '/bluelock/31.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 32', imagenUrl: '/bluelock/32.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 33', imagenUrl: '/bluelock/33.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 34', imagenUrl: '/bluelock/34.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 35', imagenUrl: '/bluelock/35.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 36', imagenUrl: '/bluelock/36.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 37', imagenUrl: '/bluelock/37.jpg', precio: 14.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 4,
    titulo: 'HUNTER X HUNTER',
    autor: 'YOSHIHIRO TOGASHI',
      tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Gon Freecss aspira a convertirse en un Cazador para encontrar a su padre desaparecido. En su viaje, se enfrenta a peligrosas pruebas y hace aliados inseparables mientras domina la misteriosa fuerza del Nen.',
    portadaUrl: '/hxh/01.jpg',
    generos: ['Acción', 'Aventura', 'Shonen'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/hxh/01.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/hxh/02.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/hxh/03.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/hxh/04.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/hxh/05.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/hxh/06.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/hxh/07.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/hxh/08.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/hxh/09.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/hxh/10.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/hxh/11.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/hxh/12.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/hxh/13.png', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 14', imagenUrl: '/hxh/14.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 15', imagenUrl: '/hxh/15.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 16', imagenUrl: '/hxh/16.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 17', imagenUrl: '/hxh/17.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 18', imagenUrl: '/hxh/18.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 19', imagenUrl: '/hxh/19.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 20', imagenUrl: '/hxh/20.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 21', imagenUrl: '/hxh/21.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 22', imagenUrl: '/hxh/22.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 23', imagenUrl: '/hxh/23.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 24', imagenUrl: '/hxh/24.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 25', imagenUrl: '/hxh/25.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 26', imagenUrl: '/hxh/26.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 27', imagenUrl: '/hxh/27.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 28', imagenUrl: '/hxh/28.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 29', imagenUrl: '/hxh/29.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 30', imagenUrl: '/hxh/30.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 31', imagenUrl: '/hxh/31.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 32', imagenUrl: '/hxh/32.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 33', imagenUrl: '/hxh/33.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 34', imagenUrl: '/hxh/34.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 35', imagenUrl: '/hxh/35.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 36', imagenUrl: '/hxh/36.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 37', imagenUrl: '/hxh/37.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 38', imagenUrl: '/hxh/38.jpg', precio: 14.50, estado: 'STOCK' },
    
    ]
  },
  {
    id: 5,
    titulo: 'DANDADAN',
    autor: 'YUKINOBU TATSU',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Momo Ayase, una chica que cree en los fantasmas, y Ken Takakura, un friki obsesionado con los alienígenas, desatan accidentalmente fuerzas ocultas y extraterrestres en una caótica y divertida lucha por recuperar sus vidas.',
    portadaUrl: '/dandadan/01.jpg',
    generos: ['Acción', 'Sobrenatural', 'Comedia', 'Romance'],
    estado: 'PREVENTA',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/dandadan/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/dandadan/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/dandadan/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/dandadan/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/dandadan/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/dandadan/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/dandadan/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/dandadan/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/dandadan/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/dandadan/10.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/dandadan/11.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/dandadan/12.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/dandadan/13.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/dandadan/14.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/dandadan/15.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 16', imagenUrl: '/dandadan/16.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 17', imagenUrl: '/dandadan/17.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 18', imagenUrl: '/dandadan/18.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 19', imagenUrl: '/dandadan/19.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 20', imagenUrl: '/dandadan/20.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 21', imagenUrl: '/dandadan/21.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 22', imagenUrl: '/dandadan/22.jpg', precio: 14.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 6,
    titulo: 'DEMON SLAYER: KIMETSU NO YAIBA',
    autor: 'KOYOHARU GOTOUGE',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Tanjiro Kamado emprende un viaje peligroso para convertirse en un cazador de demonios y encontrar la cura para devolverle la humanidad a su hermana Nezuko, la única sobreviviente del ataque que masacró a su familia.',
    portadaUrl: '/demonslayer/01.jpg',
    generos: ['Acción', 'Fantasía', 'Shonen'],
    estado: 'STOCK',
    tomos: [
      
      { numero: 'Volumen 1', imagenUrl: '/demonslayer/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/demonslayer/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/demonslayer/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/demonslayer/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/demonslayer/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/demonslayer/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/demonslayer/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/demonslayer/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/demonslayer/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/demonslayer/10.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/demonslayer/11.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/demonslayer/12.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/demonslayer/13.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/demonslayer/14.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/demonslayer/15.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 16', imagenUrl: '/demonslayer/16.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 17', imagenUrl: '/demonslayer/17.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 18', imagenUrl: '/demonslayer/18.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 19', imagenUrl: '/demonslayer/19.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 20', imagenUrl: '/demonslayer/20.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 21', imagenUrl: '/demonslayer/21.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 22', imagenUrl: '/demonslayer/22.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 23', imagenUrl: '/demonslayer/23.jpg', precio: 14.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 7,
    titulo: 'GOODBYE ERI',
    autor: 'TATSUKI FUJIMOTO',
    tipoPublicacion: 'Tomo con Sobrecubierta',
    sinopsis: 'Yuta filma los últimos días de su madre enferma a petición de ella, pero tras su muerte, el resultado de la película genera controversia, llevándolo a conocer a una misteriosa chica llamada Eri.',
    portadaUrl: '/goodbyeeri/01.jpg',
    generos: ['Drama', 'Psicológico', 'Recuentos de la vida'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Tomo Único', imagenUrl: '/goodbyeeri/01.jpg', precio: 14.50, estado: 'STOCK' }
    ]
  },
  {
    id: 8,
    titulo: 'BOCCHI THE ROCK!',
    autor: 'AKI HAMAZI',
    tipoPublicacion: 'Tomos con Sobrecubierta. A5 con páginas a color',
    sinopsis: 'Hitori Goto es una estudiante de secundaria extremadamente ansiosa y solitaria que ama la guitarra. Su vida da un giro inesperado cuando Nijika Ijichi la invita a unirse a la "Kessoku Band".',
    portadaUrl: '/bocchitherock/01.jpg',
    generos: ['Comedia', 'Música', 'Recuentos de la vida'],
    estado: 'RESERVA',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/bocchitherock/01.jpg', precio: 16.85, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/bocchitherock/02.jpg', precio: 16.85, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/bocchitherock/03.jpg', precio: 16.85, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/bocchitherock/04.jpg', precio: 16.85, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/bocchitherock/05.jpg', precio: 16.85, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/bocchitherock/06.jpg', precio: 16.85, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/bocchitherock/07.jpg', precio: 16.85, estado: 'RESERVA' }
    ]
  },
  {
    id: 9,
    titulo: 'EL PECADO ORIGINAL DE TAKOPI',
    autor: 'TAIZAN5',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Un impactante drama psicológico que narra el encuentro entre Shizuka, una niña sumida en una triste realidad escolar y familiar, y Takopi, un extraterrestre feliz e ingenuo que intenta resolver sus problemas con extraños artilugios.',
    portadaUrl: '/takopi/01.jpg',
    generos: ['Drama', 'Psicológico', 'Tragedia'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/takopi/01.jpg', precio: 15.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/takopi/02.jpg', precio: 15.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 10,
    titulo: 'FRIEREN MAS ALLÁ DEL FINAL',
    autor: ' KANEHITO YAMADA & TSUKASA ABE',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'La maga elfa Frieren y sus compañeros derrotaron al Rey Demonio. Como elfa, su esperanza de vida es inmensamente mayor, lo que la obliga a ver cómo sus antiguos camaradas envejecen y mueren, impulsándola a comprender mejor a los humanos.',
    portadaUrl: '/frieren/01.jpg',
    generos: ['Fantasía', 'Aventura', 'Drama'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/frieren/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/frieren/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/frieren/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/frieren/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/frieren/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/frieren/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/frieren/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/frieren/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/frieren/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/frieren/10.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/frieren/11.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/frieren/12.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/frieren/13.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/frieren/14.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/frieren/15.jpg', precio: 14.50, estado: 'RESERVA' }
      
    ]
  },
  {
    id: 11,
    titulo: 'FULLMETAL ALCHEMIST',
    autor: 'HIRUMO ARAKAWA',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Los hermanos Edward y Alphonse Elric rompen el mayor tabú de la alquimia al intentar resucitar a su madre. Tras pagar un precio físico devastador, inician la búsqueda de la legendaria Piedra Filosofal para restaurar sus cuerpos.',
    portadaUrl: '/fma/01.jpg',
    generos: ['Acción', 'Fantasía', 'Militar', 'Shonen'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/fma/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/fma/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/fma/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/fma/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/fma/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/fma/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/fma/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/fma/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/fma/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/fma/10.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/fma/11.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/fma/12.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/fma/13.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/fma/14.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/fma/15.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 16', imagenUrl: '/fma/16.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 17', imagenUrl: '/fma/17.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 18', imagenUrl: '/fma/18.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 19', imagenUrl: '/fma/19.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 20', imagenUrl: '/fma/20.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 21', imagenUrl: '/fma/21.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 22', imagenUrl: '/fma/22.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 23', imagenUrl: '/fma/23.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 24', imagenUrl: '/fma/24.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 25', imagenUrl: '/fma/25.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 26', imagenUrl: '/fma/26.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 27', imagenUrl: '/fma/27.jpg', precio: 14.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 12,
    titulo: 'GACHIAKUTA',
    autor: 'KEI URANA & HIDEOSHI ANDOU',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Rudo vive en las barriadas de una ciudad flotante donde los marginados conviven con la basura. Tras ser incriminado por un crimen que no cometió, es arrojado al "Abismo", un vertedero infestado de monstruos donde descubrirá un poder único.',
    portadaUrl: '/gachiakuta/01.jpg',
    generos: ['Acción', 'Fantasía', 'Urban'],
    estado: 'PREVENTA',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/gachiakuta/01.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 2', imagenUrl: '/gachiakuta/02.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 3', imagenUrl: '/gachiakuta/03.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 4', imagenUrl: '/gachiakuta/04.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 5', imagenUrl: '/gachiakuta/05.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 6', imagenUrl: '/gachiakuta/06.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 7', imagenUrl: '/gachiakuta/07.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 8', imagenUrl: '/gachiakuta/08.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 9', imagenUrl: '/gachiakuta/09.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 10', imagenUrl: '/gachiakuta/10.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 11', imagenUrl: '/gachiakuta/11.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 12', imagenUrl: '/gachiakuta/12.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 13', imagenUrl: '/gachiakuta/13.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 14', imagenUrl: '/gachiakuta/14.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 15', imagenUrl: '/gachiakuta/15.jpg', precio: 14.50, estado: 'PREVENTA' }
    ]
  },
  {
    id: 13,
    titulo: 'IRUMA-KUN EN LA ESCUELA DE DEMONIOS',
    autor: 'OSUMU NISHI',
    tipoPublicacion: 'Tomos 2EN1. B6 e incluye páginas a color',
    sinopsis: 'Iruma Suzuki es un chico amable de 14 años cuyos irresponsables padres lo venden a un demonio. Sin embargo, el demonio resulta ser un tierno anciano que decide adoptarlo como su nieto y enviarlo a la academia de demonios Babyls.',
    portadaUrl: '/irumakun/01.jpg',
    generos: ['Comedia', 'Fantasía', 'Escolar'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/irumakun/01.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/irumakun/02.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/irumakun/03.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/irumakun/04.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/irumakun/05.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/irumakun/06.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/irumakun/07.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/irumakun/08.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/irumakun/09.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/irumakun/10.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/irumakun/11.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/irumakun/12.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/irumakun/13.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/irumakun/14.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/irumakun/15.jpg', precio: 22.00, estado: 'RESERVA' }
    ]
  },
  {
    id: 14,
    titulo: 'KAIJU Nº8',
    autor: 'NAOYA MATSUMOTO',
    tipoPublicacion: 'Tomos con Sobrecubierta e incluye páginas a color',
    sinopsis: 'Kafka Hibino trabaja limpiando los restos de los Kaijus derrotados, frustrado por no cumplir su sueño de unirse a las Fuerzas de Defensa. Todo cambia cuando un pequeño Kaiju parasitario ingresa a su cuerpo, otorgándole poderes titánicos.',
    portadaUrl: '/kaiju8/01.jpg',
    generos: ['Acción', 'Militar', 'Ciencia Ficción'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/kaiju8/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/kaiju8/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/kaiju8/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/kaiju8/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/kaiju8/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/kaiju8/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/kaiju8/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/kaiju8/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/kaiju8/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/kaiju8/10.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/kaiju8/11.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/kaiju8/12.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/kaiju8/13.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/kaiju8/14.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/kaiju8/15.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 16', imagenUrl: '/kaiju8/16.jpg', precio: 14.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 15,
    titulo: 'KAGURABACHI',
    autor: 'TAKERU HOKAZONO',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'El joven Chihiro pasa sus días entrenando bajo la tutela de su padre, un herrero de espadas legendario. Impulsado por una cruel tragedia del pasado, Chihiro empuña una espada mística impregnada de magia de sangre para buscar venganza.',
    portadaUrl: '/kagurabachi/01.jpg',
    generos: ['Acción', 'Fantasía Oscura', 'Drama'],
    estado: 'PREVENTA',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/kagurabachi/01.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 2', imagenUrl: '/kagurabachi/02.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 3', imagenUrl: '/kagurabachi/03.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 4', imagenUrl: '/kagurabachi/04.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 5', imagenUrl: '/kagurabachi/05.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 6', imagenUrl: '/kagurabachi/06.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 7', imagenUrl: '/kagurabachi/07.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 8', imagenUrl: '/kagurabachi/08.jpg', precio: 14.50, estado: 'PREVENTA' }      
    ]
  },
  {
    id: 16,
    titulo: 'KILL BLUE',
    autor: 'TADATOSHI FUJIMAKI',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Oogami Juzo, un legendario asesino a sueldo de mediana edad, es víctima de un misterioso experimento con avispas modificadas que rejuvenece su cuerpo hasta el de un estudiante de secundaria, obligándolo a volver a las aulas.',
    portadaUrl: '/killblue/01.jpg',
    generos: ['Acción', 'Comedia', 'Escolar'],
    estado: 'RESERVA',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/killblue/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/killblue/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/killblue/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/killblue/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/killblue/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/killblue/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/killblue/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/killblue/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/killblue/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/killblue/10.jpg', precio: 14.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 17,
    titulo: 'KONOSUBA',
    autor: ' NATSUME AKATSUKI & MASAHITO WATARI + KURONE MISHIMA ',
    tipoPublicacion: 'Tomos 2EN1. B6 e incluye páginas a color',
    sinopsis: 'Kazuma Sato muere de una forma ridícula y despierta ante la diosa Aqua, quien le ofrece reencarnar en un mundo de fantasía RPG. Desafortunadamente para él, elige llevarse a la inútil diosa como su "objeto" de ayuda, iniciando una vida de deudas y caos.',
    portadaUrl: '/konosuba/01.jpg',
    generos: ['Comedia', 'Fantasía', 'Isekai'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/konosuba/01.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/konosuba/02.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/konosuba/03.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/konosuba/04.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/konosuba/05.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/konosuba/06.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/konosuba/07.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/konosuba/08.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/konosuba/09.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/konosuba/10.jpg', precio: 22.00, estado: 'STOCK' }
    ]
  }
  ];

  private mangasSubject = new BehaviorSubject<Manga[]>(this.mangasMock);
  
  getMangas(): Observable<Manga[]> {
    return this.mangasSubject.asObservable();
  }

  getGenerosDisponibles(): string[] {
    const todosLosGeneros = this.mangasMock.flatMap(m => m.generos);
    return [...new Set(todosLosGeneros)];
  }
}