import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import { Manga } from '../components/models/models';


@Injectable({
  providedIn: 'root'
})
export class MangaService {
  private mangasMock: Manga[] = [
    {
      id: 1,
      titulo: 'CHAINSAW MAN',
      autor: 'TATSUKI FUJIMOTO',
      tipoPublicacion: 'Tomos con Sobrecubierta',
      sinopsis: 'Denji es un chico pobre capaz de hacer cualquier cosa por dinero, incluso cazar demonios con su perro demonio Pochita.',
      portadaUrl: '/chainsawman/01.jpg',
      generos: ['Acción', 'Sobrenatural', 'Shonen'],
      estado: 'RESERVA',
      tomos: [
        { numero: 'Volumen 1', imagenUrl: '/chainsawman/01.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 2', imagenUrl: '/chainsawman/02.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 3', imagenUrl: '/chainsawman/03.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 4', imagenUrl: '/chainsawman/04.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 5', imagenUrl: '/chainsawman/05.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 6', imagenUrl: '/chainsawman/06.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 7', imagenUrl: '/chainsawman/07.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 8', imagenUrl: '/chainsawman/08.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 9', imagenUrl: '/chainsawman/09.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 10', imagenUrl: '/chainsawman/10.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 11', imagenUrl: '/chainsawman/11.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 12', imagenUrl: '/chainsawman/12.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 13', imagenUrl: '/chainsawman/13.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 14', imagenUrl: '/chainsawman/14.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 14 - Especial', imagenUrl: '/chainsawman/14-especial.jpg', precio: 17.25, estado: 'RESERVA' },
        { numero: 'Volumen 15', imagenUrl: '/chainsawman/15.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 16', imagenUrl: '/chainsawman/16.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 17', imagenUrl: '/chainsawman/17.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 18', imagenUrl: '/chainsawman/18.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 19', imagenUrl: '/chainsawman/19.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 20', imagenUrl: '/chainsawman/20.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 21', imagenUrl: '/chainsawman/21.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 22', imagenUrl: '/chainsawman/22.jpg', precio: 14.50, estado: 'RESERVA' },
        { numero: 'Volumen 23', imagenUrl: '/chainsawman/23.jpg', precio: 14.50, estado: 'RESERVA' }
      ]
    },
    {
      id: 2,
      titulo: 'FUMANDO ATRÁS DEL SÚPER CON VOS',
      autor: 'JINUSHI',
      tipoPublicacion: 'Tomos con Sobrecubierta. B6 e incluye páginas a color',
      sinopsis: 'Sasaki es un oficinista estresado cuyo único refugio diario es Yamada, la alegre cajera de su supermercado favorito. Un día, tras una jornada especialmente dura, Sasaki no la encuentra en su turno. Al salir desanimado a buscar un lugar para fumar, se topa con Tayama, una chica con estilo alternativo que lo invita a compartir un cigarrillo en la zona trasera del local. Lo que Sasaki no sabe es que Tayama y Yamada son la misma persona.',
      portadaUrl: '/fumando/01.jpg',
      generos: ['Comedia', 'Recuentos de la vida', 'Romance'],
      estado: 'RESERVA',
      tomos: [
        { numero: 'Volumen 1', imagenUrl: '/fumando/01.jpg', precio: 16.75, estado: 'PREVENTA' }, 
        { numero: 'Volumen 2', imagenUrl: '/fumando/02.jpg', precio: 16.75, estado: 'RESERVA' },
        { numero: 'Volumen 3', imagenUrl: '/fumando/03.jpg', precio: 16.75, estado: 'PREVENTA' }, 
        { numero: 'Volumen 4', imagenUrl: '/fumando/04.jpg', precio: 16.75, estado: 'RESERVA' },
        { numero: 'Volumen 5', imagenUrl: '/fumando/05.jpg', precio: 16.75, estado: 'PREVENTA' }, 
        { numero: 'Volumen 6', imagenUrl: '/fumando/06.jpg', precio: 16.75, estado: 'RESERVA' },
        { numero: 'Volumen 7', imagenUrl: '/fumando/07.jpg', precio: 16.75, estado: 'PREVENTA' }, 
        { numero: 'Volumen 8', imagenUrl: '/fumando/08.jpg', precio: 16.75, estado: 'RESERVA' }
      ]
    },
  {
    id: 3,
    titulo: 'BLUE LOCK',
    autor: 'MUNEYUKI KANESHIRO & YUSUKE NOMURA',
      tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Tras la eliminación de Japón en el Mundial de 2018, la unión de fútbol japonesa contrata a Jinpachi Ego para crear un programa que produzca al delantero egoísta definitivo capaz de guiar al país a la gloria.',
    portadaUrl: '/bluelock/01.jpg',
    generos: ['Deportes', 'Drama', 'Shonen'],
    estado: 'RESERVA',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/bluelock/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/bluelock/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/bluelock/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/bluelock/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/bluelock/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/bluelock/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/bluelock/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/bluelock/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/bluelock/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/bluelock/10.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/bluelock/11.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/bluelock/12.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/bluelock/13.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/bluelock/14.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/bluelock/15.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 16', imagenUrl: '/bluelock/16.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 17', imagenUrl: '/bluelock/17.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 18', imagenUrl: '/bluelock/18.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 19', imagenUrl: '/bluelock/19.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 20', imagenUrl: '/bluelock/20.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 21', imagenUrl: '/bluelock/21.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 22', imagenUrl: '/bluelock/22.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 23', imagenUrl: '/bluelock/23.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 24', imagenUrl: '/bluelock/24.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 25', imagenUrl: '/bluelock/25.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 26', imagenUrl: '/bluelock/26.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 27', imagenUrl: '/bluelock/27.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 28', imagenUrl: '/bluelock/28.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 29', imagenUrl: '/bluelock/29.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 30', imagenUrl: '/bluelock/30.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 31', imagenUrl: '/bluelock/31.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 32', imagenUrl: '/bluelock/32.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 33', imagenUrl: '/bluelock/33.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 34', imagenUrl: '/bluelock/34.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 35', imagenUrl: '/bluelock/35.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 36', imagenUrl: '/bluelock/36.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 37', imagenUrl: '/bluelock/37.jpg', precio: 14.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 4,
    titulo: 'HUNTER X HUNTER',
    autor: 'YOSHIHIRO TOGASHI',
      tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Gon Freecss aspira a convertirse en un Cazador para encontrar a su padre desaparecido. En su viaje, se enfrenta a peligrosas pruebas y hace aliados inseparables mientras domina la misteriosa fuerza del Nen.',
    portadaUrl: '/hxh/01.jpg',
    generos: ['Acción', 'Aventura', 'Shonen'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/hxh/01.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/hxh/02.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/hxh/03.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/hxh/04.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/hxh/05.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/hxh/06.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/hxh/07.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/hxh/08.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/hxh/09.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/hxh/10.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/hxh/11.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/hxh/12.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/hxh/13.png', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 14', imagenUrl: '/hxh/14.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 15', imagenUrl: '/hxh/15.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 16', imagenUrl: '/hxh/16.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 17', imagenUrl: '/hxh/17.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 18', imagenUrl: '/hxh/18.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 19', imagenUrl: '/hxh/19.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 20', imagenUrl: '/hxh/20.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 21', imagenUrl: '/hxh/21.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 22', imagenUrl: '/hxh/22.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 23', imagenUrl: '/hxh/23.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 24', imagenUrl: '/hxh/24.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 25', imagenUrl: '/hxh/25.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 26', imagenUrl: '/hxh/26.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 27', imagenUrl: '/hxh/27.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 28', imagenUrl: '/hxh/28.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 29', imagenUrl: '/hxh/29.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 30', imagenUrl: '/hxh/30.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 31', imagenUrl: '/hxh/31.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 32', imagenUrl: '/hxh/32.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 33', imagenUrl: '/hxh/33.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 34', imagenUrl: '/hxh/34.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 35', imagenUrl: '/hxh/35.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 36', imagenUrl: '/hxh/36.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 37', imagenUrl: '/hxh/37.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 38', imagenUrl: '/hxh/38.jpg', precio: 14.50, estado: 'STOCK' },
    
    ]
  },
  {
    id: 5,
    titulo: 'DANDADAN',
    autor: 'YUKINOBU TATSU',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Momo Ayase, una chica que cree en los fantasmas, y Ken Takakura, un friki obsesionado con los alienígenas, desatan accidentalmente fuerzas ocultas y extraterrestres en una caótica y divertida lucha por recuperar sus vidas.',
    portadaUrl: '/dandadan/01.jpg',
    generos: ['Acción', 'Sobrenatural', 'Comedia', 'Romance'],
    estado: 'PREVENTA',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/dandadan/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/dandadan/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/dandadan/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/dandadan/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/dandadan/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/dandadan/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/dandadan/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/dandadan/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/dandadan/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/dandadan/10.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/dandadan/11.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/dandadan/12.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/dandadan/13.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/dandadan/14.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/dandadan/15.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 16', imagenUrl: '/dandadan/16.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 17', imagenUrl: '/dandadan/17.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 18', imagenUrl: '/dandadan/18.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 19', imagenUrl: '/dandadan/19.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 20', imagenUrl: '/dandadan/20.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 21', imagenUrl: '/dandadan/21.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 22', imagenUrl: '/dandadan/22.jpg', precio: 14.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 6,
    titulo: 'DEMON SLAYER: KIMETSU NO YAIBA',
    autor: 'KOYOHARU GOTOUGE',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Tanjiro Kamado emprende un viaje peligroso para convertirse en un cazador de demonios y encontrar la cura para devolverle la humanidad a su hermana Nezuko, la única sobreviviente del ataque que masacró a su familia.',
    portadaUrl: '/demonslayer/01.jpg',
    generos: ['Acción', 'Fantasía', 'Shonen'],
    estado: 'STOCK',
    tomos: [
      
      { numero: 'Volumen 1', imagenUrl: '/demonslayer/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/demonslayer/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/demonslayer/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/demonslayer/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/demonslayer/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/demonslayer/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/demonslayer/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/demonslayer/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/demonslayer/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/demonslayer/10.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/demonslayer/11.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/demonslayer/12.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/demonslayer/13.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/demonslayer/14.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/demonslayer/15.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 16', imagenUrl: '/demonslayer/16.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 17', imagenUrl: '/demonslayer/17.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 18', imagenUrl: '/demonslayer/18.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 19', imagenUrl: '/demonslayer/19.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 20', imagenUrl: '/demonslayer/20.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 21', imagenUrl: '/demonslayer/21.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 22', imagenUrl: '/demonslayer/22.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 23', imagenUrl: '/demonslayer/23.jpg', precio: 14.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 7,
    titulo: 'GOODBYE ERI',
    autor: 'TATSUKI FUJIMOTO',
    tipoPublicacion: 'Tomo con Sobrecubierta',
    sinopsis: 'Yuta filma los últimos días de su madre enferma a petición de ella, pero tras su muerte, el resultado de la película genera controversia, llevándolo a conocer a una misteriosa chica llamada Eri.',
    portadaUrl: '/goodbyeeri/01.jpg',
    generos: ['Drama', 'Psicológico', 'Recuentos de la vida'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Tomo Único', imagenUrl: '/goodbyeeri/01.jpg', precio: 14.50, estado: 'STOCK' }
    ]
  },
  {
    id: 8,
    titulo: 'BOCCHI THE ROCK!',
    autor: 'AKI HAMAZI',
    tipoPublicacion: 'Tomos con Sobrecubierta. A5 con páginas a color',
    sinopsis: 'Hitori Goto es una estudiante de secundaria extremadamente ansiosa y solitaria que ama la guitarra. Su vida da un giro inesperado cuando Nijika Ijichi la invita a unirse a la "Kessoku Band".',
    portadaUrl: '/bocchitherock/01.jpg',
    generos: ['Comedia', 'Música', 'Recuentos de la vida'],
    estado: 'RESERVA',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/bocchitherock/01.jpg', precio: 16.85, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/bocchitherock/02.jpg', precio: 16.85, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/bocchitherock/03.jpg', precio: 16.85, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/bocchitherock/04.jpg', precio: 16.85, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/bocchitherock/05.jpg', precio: 16.85, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/bocchitherock/06.jpg', precio: 16.85, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/bocchitherock/07.jpg', precio: 16.85, estado: 'RESERVA' }
    ]
  },
  {
    id: 9,
    titulo: 'EL PECADO ORIGINAL DE TAKOPI',
    autor: 'TAIZAN5',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Un impactante drama psicológico que narra el encuentro entre Shizuka, una niña sumida en una triste realidad escolar y familiar, y Takopi, un extraterrestre feliz e ingenuo que intenta resolver sus problemas con extraños artilugios.',
    portadaUrl: '/takopi/01.jpg',
    generos: ['Drama', 'Psicológico', 'Tragedia'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/takopi/01.jpg', precio: 15.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/takopi/02.jpg', precio: 15.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 10,
    titulo: 'FRIEREN MAS ALLÁ DEL FINAL',
    autor: ' KANEHITO YAMADA & TSUKASA ABE',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'La maga elfa Frieren y sus compañeros derrotaron al Rey Demonio. Como elfa, su esperanza de vida es inmensamente mayor, lo que la obliga a ver cómo sus antiguos camaradas envejecen y mueren, impulsándola a comprender mejor a los humanos.',
    portadaUrl: '/frieren/01.jpg',
    generos: ['Fantasía', 'Aventura', 'Drama'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/frieren/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/frieren/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/frieren/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/frieren/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/frieren/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/frieren/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/frieren/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/frieren/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/frieren/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/frieren/10.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/frieren/11.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/frieren/12.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/frieren/13.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/frieren/14.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/frieren/15.jpg', precio: 14.50, estado: 'RESERVA' }
      
    ]
  },
  {
    id: 11,
    titulo: 'FULLMETAL ALCHEMIST',
    autor: 'HIRUMO ARAKAWA',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Los hermanos Edward y Alphonse Elric rompen el mayor tabú de la alquimia al intentar resucitar a su madre. Tras pagar un precio físico devastador, inician la búsqueda de la legendaria Piedra Filosofal para restaurar sus cuerpos.',
    portadaUrl: '/fma/01.jpg',
    generos: ['Acción', 'Fantasía', 'Militar', 'Shonen'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/fma/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/fma/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/fma/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/fma/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/fma/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/fma/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/fma/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/fma/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/fma/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/fma/10.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/fma/11.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/fma/12.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/fma/13.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/fma/14.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/fma/15.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 16', imagenUrl: '/fma/16.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 17', imagenUrl: '/fma/17.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 18', imagenUrl: '/fma/18.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 19', imagenUrl: '/fma/19.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 20', imagenUrl: '/fma/20.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 21', imagenUrl: '/fma/21.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 22', imagenUrl: '/fma/22.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 23', imagenUrl: '/fma/23.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 24', imagenUrl: '/fma/24.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 25', imagenUrl: '/fma/25.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 26', imagenUrl: '/fma/26.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 27', imagenUrl: '/fma/27.jpg', precio: 14.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 12,
    titulo: 'GACHIAKUTA',
    autor: 'KEI URANA & HIDEOSHI ANDOU',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Rudo vive en las barriadas de una ciudad flotante donde los marginados conviven con la basura. Tras ser incriminado por un crimen que no cometió, es arrojado al "Abismo", un vertedero infestado de monstruos donde descubrirá un poder único.',
    portadaUrl: '/gachiakuta/01.jpg',
    generos: ['Acción', 'Fantasía', 'Urban'],
    estado: 'PREVENTA',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/gachiakuta/01.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 2', imagenUrl: '/gachiakuta/02.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 3', imagenUrl: '/gachiakuta/03.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 4', imagenUrl: '/gachiakuta/04.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 5', imagenUrl: '/gachiakuta/05.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 6', imagenUrl: '/gachiakuta/06.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 7', imagenUrl: '/gachiakuta/07.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 8', imagenUrl: '/gachiakuta/08.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 9', imagenUrl: '/gachiakuta/09.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 10', imagenUrl: '/gachiakuta/10.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 11', imagenUrl: '/gachiakuta/11.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 12', imagenUrl: '/gachiakuta/12.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 13', imagenUrl: '/gachiakuta/13.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 14', imagenUrl: '/gachiakuta/14.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 15', imagenUrl: '/gachiakuta/15.jpg', precio: 14.50, estado: 'PREVENTA' }
    ]
  },
  {
    id: 13,
    titulo: 'IRUMA-KUN EN LA ESCUELA DE DEMONIOS',
    autor: 'OSUMU NISHI',
    tipoPublicacion: 'Tomos 2EN1. B6 e incluye páginas a color',
    sinopsis: 'Iruma Suzuki es un chico amable de 14 años cuyos irresponsables padres lo venden a un demonio. Sin embargo, el demonio resulta ser un tierno anciano que decide adoptarlo como su nieto y enviarlo a la academia de demonios Babyls.',
    portadaUrl: '/irumakun/01.jpg',
    generos: ['Comedia', 'Fantasía', 'Escolar'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/irumakun/01.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/irumakun/02.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/irumakun/03.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/irumakun/04.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/irumakun/05.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/irumakun/06.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/irumakun/07.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/irumakun/08.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/irumakun/09.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/irumakun/10.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/irumakun/11.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/irumakun/12.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/irumakun/13.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/irumakun/14.jpg', precio: 22.00, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/irumakun/15.jpg', precio: 22.00, estado: 'RESERVA' }
    ]
  },
  {
    id: 14,
    titulo: 'KAIJU Nº8',
    autor: 'NAOYA MATSUMOTO',
    tipoPublicacion: 'Tomos con Sobrecubierta e incluye páginas a color',
    sinopsis: 'Kafka Hibino trabaja limpiando los restos de los Kaijus derrotados, frustrado por no cumplir su sueño de unirse a las Fuerzas de Defensa. Todo cambia cuando un pequeño Kaiju parasitario ingresa a su cuerpo, otorgándole poderes titánicos.',
    portadaUrl: '/kaiju8/01.jpg',
    generos: ['Acción', 'Militar', 'Ciencia Ficción'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/kaiju8/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/kaiju8/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/kaiju8/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/kaiju8/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/kaiju8/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/kaiju8/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/kaiju8/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/kaiju8/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/kaiju8/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/kaiju8/10.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 11', imagenUrl: '/kaiju8/11.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 12', imagenUrl: '/kaiju8/12.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 13', imagenUrl: '/kaiju8/13.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 14', imagenUrl: '/kaiju8/14.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 15', imagenUrl: '/kaiju8/15.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 16', imagenUrl: '/kaiju8/16.jpg', precio: 14.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 15,
    titulo: 'KAGURABACHI',
    autor: 'TAKERU HOKAZONO',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'El joven Chihiro pasa sus días entrenando bajo la tutela de su padre, un herrero de espadas legendario. Impulsado por una cruel tragedia del pasado, Chihiro empuña una espada mística impregnada de magia de sangre para buscar venganza.',
    portadaUrl: '/kagurabachi/01.jpg',
    generos: ['Acción', 'Fantasía Oscura', 'Drama'],
    estado: 'PREVENTA',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/kagurabachi/01.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 2', imagenUrl: '/kagurabachi/02.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 3', imagenUrl: '/kagurabachi/03.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 4', imagenUrl: '/kagurabachi/04.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 5', imagenUrl: '/kagurabachi/05.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 6', imagenUrl: '/kagurabachi/06.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 7', imagenUrl: '/kagurabachi/07.jpg', precio: 14.50, estado: 'PREVENTA' },
      { numero: 'Volumen 8', imagenUrl: '/kagurabachi/08.jpg', precio: 14.50, estado: 'PREVENTA' }      
    ]
  },
  {
    id: 16,
    titulo: 'KILL BLUE',
    autor: 'TADATOSHI FUJIMAKI',
    tipoPublicacion: 'Tomos con Sobrecubierta',
    sinopsis: 'Oogami Juzo, un legendario asesino a sueldo de mediana edad, es víctima de un misterioso experimento con avispas modificadas que rejuvenece su cuerpo hasta el de un estudiante de secundaria, obligándolo a volver a las aulas.',
    portadaUrl: '/killblue/01.jpg',
    generos: ['Acción', 'Comedia', 'Escolar'],
    estado: 'RESERVA',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/killblue/01.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 2', imagenUrl: '/killblue/02.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 3', imagenUrl: '/killblue/03.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 4', imagenUrl: '/killblue/04.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 5', imagenUrl: '/killblue/05.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 6', imagenUrl: '/killblue/06.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 7', imagenUrl: '/killblue/07.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 8', imagenUrl: '/killblue/08.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 9', imagenUrl: '/killblue/09.jpg', precio: 14.50, estado: 'RESERVA' },
      { numero: 'Volumen 10', imagenUrl: '/killblue/10.jpg', precio: 14.50, estado: 'RESERVA' }
    ]
  },
  {
    id: 17,
    titulo: 'KONOSUBA',
    autor: ' NATSUME AKATSUKI & MASAHITO WATARI + KURONE MISHIMA ',
    tipoPublicacion: 'Tomos 2EN1. B6 e incluye páginas a color',
    sinopsis: 'Kazuma Sato muere de una forma ridícula y despierta ante la diosa Aqua, quien le ofrece reencarnar en un mundo de fantasía RPG. Desafortunadamente para él, elige llevarse a la inútil diosa como su "objeto" de ayuda, iniciando una vida de deudas y caos.',
    portadaUrl: '/konosuba/01.jpg',
    generos: ['Comedia', 'Fantasía', 'Isekai'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/konosuba/01.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/konosuba/02.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/konosuba/03.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/konosuba/04.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/konosuba/05.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/konosuba/06.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/konosuba/07.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/konosuba/08.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/konosuba/09.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/konosuba/10.jpg', precio: 22.00, estado: 'STOCK' }
    ]
  },

  {
    id: 18,
    titulo: 'ANOTHER',
    autor: 'YUKITO AYATSUJI & HIRO KIYOHARA',
    tipoPublicacion: 'Tomos B6 con sobrecubierta e incluye paginas a color',
    sinopsis: 'En 1972, una popular estudiante llamada Misaki falleció a mitad del año escolar. Al llegar a la clase 3-3 en 1998, Koichi Sakakibara siente una atmósfera misteriosa y se siente atraído por Mei Misaki, una chica que lleva un parche en el ojo y a quien todos parecen ignorar.',
    portadaUrl: '/another/01.jpg',
    generos: ['Misterio', 'Terror', 'Sobrenatural'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/another/01.jpg', precio: 15.50, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/another/02.jpg', precio: 15.50, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/another/03.jpg', precio: 15.50, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/another/04.jpg', precio: 15.50, estado: 'STOCK' }
    ]
  },
  {
    id: 19,
    titulo: 'BAKI THE GRAPPLER - EDICIÓN KANZENBAN',
    autor: 'KEISUKE ITAGAKI',
    tipoPublicacion: 'Tomos A5 con sobrecubierta e incluye páginas a color',
    sinopsis: 'Baki Hanma entrena intensamente para superar a su padre, Yujiro Hanma, el ser más fuerte del planeta. En su camino se enfrentará a los luchadores más formidables del mundo en combates a muerte sin reglas.',
    portadaUrl: '/baki/01.jpg',
    generos: ['Artes Marciales', 'Acción', 'Shonen'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/baki/01.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/baki/02.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/baki/03.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/baki/04.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/baki/05.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/baki/06.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/baki/07.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/baki/08.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/baki/09.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/baki/10.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/baki/11.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/baki/12.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/baki/13.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 14', imagenUrl: '/baki/14.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 15', imagenUrl: '/baki/15.jpg', precio: 28.00, estado: 'STOCK' }
    ]
  },
  {
    id: 20,
    titulo: 'AYAKASHI TRIANGLE',
    autor: 'KENTARO YABUKI',
    tipoPublicacion: 'Tomos simples con sobrecubierta',
    sinopsis: 'Matsuri Kazamaki es un ninja exorcista que protege a su amiga de la infancia, Suzu, de los espíritus malignos llamados Ayakashi. Sin embargo, tras un enfrentamiento con el rey de los Ayakashi, ¡Matsuri es transformado en chica!',
    portadaUrl: '/ayakashi-triangle/01.jpg',
    generos: ['Comedia', 'Romance', 'Ecchi', 'Sobrenatural'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/ayakashi-triangle/01.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/ayakashi-triangle/02.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/ayakashi-triangle/03.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/ayakashi-triangle/04.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/ayakashi-triangle/05.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/ayakashi-triangle/06.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/ayakashi-triangle/07.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/ayakashi-triangle/08.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/ayakashi-triangle/09.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/ayakashi-triangle/10.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/ayakashi-triangle/11.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/ayakashi-triangle/12.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/ayakashi-triangle/13.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 14', imagenUrl: '/ayakashi-triangle/14.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 15', imagenUrl: '/ayakashi-triangle/15.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 16', imagenUrl: '/ayakashi-triangle/16.jpg', precio: 14.50, estado: 'STOCK' }
    ]
  },
  {
    id: 21,
    titulo: 'CALL OF THE NIGHT',
    autor: 'KOTOYAMA',
    tipoPublicacion: 'Tomos simples con sobrecubierta',
    sinopsis: 'Ko Yamori es un estudiante de secundaria insomne que decide deambular por las calles de noche. Allí conoce a Nazuna Nanakusa, una vampiresa coqueta que le mostrará los placeres de la vida nocturna, haciendo que Ko también quiera convertirse en vampiro.',
    portadaUrl: '/call-of-the-night/01.jpg',
    generos: ['Romance', 'Sobrenatural', 'Recuentos de la vida'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/call-of-the-night/01.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/call-of-the-night/02.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/call-of-the-night/03.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/call-of-the-night/04.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/call-of-the-night/05.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/call-of-the-night/06.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/call-of-the-night/07.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/call-of-the-night/08.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/call-of-the-night/09.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/call-of-the-night/10.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/call-of-the-night/11.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/call-of-the-night/12.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/call-of-the-night/13.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 14', imagenUrl: '/call-of-the-night/14.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 15', imagenUrl: '/call-of-the-night/15.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 16', imagenUrl: '/call-of-the-night/16.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 17', imagenUrl: '/call-of-the-night/17.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 18', imagenUrl: '/call-of-the-night/18.jpg', precio: 14.50, estado: 'STOCK' }
    ]
  },
  {
    id: 22,
    titulo: 'BLEACH',
    autor: 'TITE KUBO',
    tipoPublicacion: 'Edicion Remix. Tomos B6 con sobrecubierta e incluye desplegable a color',
    sinopsis: 'Ichigo Kurosaki es un estudiante de preparatoria que puede ver fantasmas. Su vida cambia por completo cuando conoce a Rukia Kuchiki, una Shinigami (dios de la muerte), y absorbe sus poderes para proteger a su familia de los monstruos llamados Hollows.',
    portadaUrl: '/bleach/01.jpg',
    generos: ['Acción', 'Aventura', 'Sobrenatural', 'Shonen'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/bleach/01.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/bleach/02.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/bleach/03.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/bleach/04.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/bleach/05.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/bleach/06.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/bleach/07.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/bleach/08.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/bleach/09.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/bleach/10.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/bleach/11.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/bleach/12.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/bleach/13.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 14', imagenUrl: '/bleach/14.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 15', imagenUrl: '/bleach/15.jpg', precio: 27.00, estado: 'STOCK' },
      { numero: 'Volumen 16', imagenUrl: '/bleach/16.jpg', precio: 27.00, estado: 'STOCK' }
    ]
  },
  {
    id: 23,
    titulo: 'DEATH NOTE',
    autor: 'TSUGUMI OHBA & TAKESHI OBATA',
    tipoPublicacion: 'Tomos simples con sobrecubierta. Sobrecubierta con tinta metalizada',
    sinopsis: 'Light Yagami, un estudiante modelo brillante, encuentra un misterioso cuaderno que tiene el poder de matar a cualquier persona cuyo nombre sea escrito en él. Light decide usarlo para limpiar el mundo de criminales bajo el alias de "Kira", desatando un juego del gato y el ratón con el detective "L".',
    portadaUrl: '/death-note/01.jpg',
    generos: ['Misterio', 'Psicológico', 'Thriller', 'Sobrenatural'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/death-note/01.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/death-note/02.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/death-note/03.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/death-note/04.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/death-note/05.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/death-note/06.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/death-note/07.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/death-note/08.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/death-note/09.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/death-note/10.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/death-note/11.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/death-note/12.jpg', precio: 14.50, estado: 'STOCK' }
    ]
  },
  {
    id: 24,
    titulo: 'DRAGON BALL SUPER',
    autor: 'AKIRA TORIYAMA & TOYOTARO',
    tipoPublicacion: 'Tomos simples con sobrecubierta',
    sinopsis: 'Tras la derrota de Majin Buu, la Tierra disfruta de un periodo de paz. Sin embargo, esta tranquilidad se ve interrumpida por el despertar de Beerus, el Dios de la Destrucción, quien busca al legendario Dios Super Saiyan.',
    portadaUrl: '/dragon-ball-super/01.jpg',
    generos: ['Acción', 'Aventura', 'Ciencia Ficción', 'Shonen'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/dragon-ball-super/01.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/dragon-ball-super/02.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/dragon-ball-super/03.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/dragon-ball-super/04.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/dragon-ball-super/05.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/dragon-ball-super/06.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/dragon-ball-super/07.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/dragon-ball-super/08.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/dragon-ball-super/09.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/dragon-ball-super/10.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/dragon-ball-super/11.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/dragon-ball-super/12.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/dragon-ball-super/13.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 14', imagenUrl: '/dragon-ball-super/14.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 15', imagenUrl: '/dragon-ball-super/15.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 16', imagenUrl: '/dragon-ball-super/16.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 17', imagenUrl: '/dragon-ball-super/17.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 18', imagenUrl: '/dragon-ball-super/18.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 20', imagenUrl: '/dragon-ball-super/20.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 21', imagenUrl: '/dragon-ball-super/21.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 22', imagenUrl: '/dragon-ball-super/22.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 23', imagenUrl: '/dragon-ball-super/23.jpg', precio: 14.50, estado: 'STOCK' },
      { numero: 'Volumen 24', imagenUrl: '/dragon-ball-super/24.jpg', precio: 14.50, estado: 'STOCK' }
    ]
  },
  {
    id: 25,
    titulo: 'FIRE PUNCH',
    autor: 'TATSUKI FUJIMOTO',
    tipoPublicacion: 'Tomos simples con sobrecubierta',
    sinopsis: 'En un mundo congelado e inhóspito, Agni y su hermana Luna son "bendecidos" con el poder de la regeneración. Cuando un militar quema su aldea con llamas inextinguibles que consumen todo, Agni sobrevive gracias a su regeneración, quedando envuelto en un fuego eterno y buscando venganza.',
    portadaUrl: '/fire-punch/01.jpg',
    generos: ['Acción', 'Post-apocalíptico', 'Gore', 'Tragedia'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/fire-punch/01.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/fire-punch/02.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/fire-punch/03.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/fire-punch/04.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/fire-punch/05.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/fire-punch/06.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/fire-punch/07.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/fire-punch/08.jpg', precio: 15.00, estado: 'STOCK' },
      
    ]
  },
  {
    id: 26,
    titulo: 'GIRLFRIEND & GIRLFRIEND',
    autor: 'HIROYUKI',
    tipoPublicacion: 'Tomos Tankobon estándar',
    sinopsis: 'Naoya Mukai finalmente logra salir con su amiga de la infancia, Saki. Sin embargo, otra hermosa chica llamada Nagisa se le declara. En lugar de rechazarla, Naoya propone una solución descabellada: ¡salir con las dos al mismo tiempo con el consentimiento de ambas!',
    portadaUrl: '/girlfriend-girlfriend/01.jpg',
    generos: ['Comedia', 'Romance', 'Harem', 'Escolar'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/girlfriend-girlfriend/01.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/girlfriend-girlfriend/02.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/girlfriend-girlfriend/03.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/girlfriend-girlfriend/04.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/girlfriend-girlfriend/05.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/girlfriend-girlfriend/06.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/girlfriend-girlfriend/07.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/girlfriend-girlfriend/08.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/girlfriend-girlfriend/09.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/girlfriend-girlfriend/10.jpg', precio: 15.00, estado: 'STOCK' }
    ]
  },
  {
    id: 27,
    titulo: 'JIGOKURAKU - HELL’S PARADISE',
    autor: 'YUJI KAKU',
    tipoPublicacion: 'Tomos simples con sobrecubierta',
    sinopsis: 'Gabimaru el Vacío, un letal ninja condenado a muerte, recibe la oportunidad de ser indultado si viaja a una isla misteriosa y paradisíaca a recuperar el Elíxir de la Inmortalidad junto a la verdugo Yamada Asaemon Sagiri. El problema es que nadie ha regresado con vida de allí.',
    portadaUrl: '/jigokuraku/01.jpg',
    generos: ['Acción', 'Fantasía Oscura', 'Histórico', 'Gore'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/jigokuraku/01.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/jigokuraku/02.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/jigokuraku/03.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/jigokuraku/04.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/jigokuraku/05.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/jigokuraku/06.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/jigokuraku/07.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/jigokuraku/08.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/jigokuraku/09.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/jigokuraku/10.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/jigokuraku/11.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/jigokuraku/12.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/jigokuraku/13.jpg', precio: 15.00, estado: 'STOCK' }
    ]
  },
  {
    id: 28,
    titulo: 'SOLO LEVELING',
    autor: 'CHUGONG & DUBU (REDICE STUDIO)',
    tipoPublicacion: 'Tomos B6 con solapa. Integramente a color',
    sinopsis: 'En un mundo donde cazadores humanos deben luchar contra monstruos en mazmorras, Sung Jin-Woo es el cazador de rango E más débil de todos. Tras quedar al borde de la muerte en una mazmorra doble, despierta con una interfaz de "sistema" única que le permite subir de nivel sin límites.',
    portadaUrl: '/solo-leveling/01.jpg',
    generos: ['Acción', 'Fantasía', 'Sistema', 'Manhwa'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/solo-leveling/01.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/solo-leveling/02.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/solo-leveling/03.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/solo-leveling/04.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/solo-leveling/05.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/solo-leveling/06.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/solo-leveling/07.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/solo-leveling/08.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/solo-leveling/09.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/solo-leveling/10.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/solo-leveling/11.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/solo-leveling/12.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/solo-leveling/13.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 14', imagenUrl: '/solo-leveling/14.jpg', precio: 28.00, estado: 'STOCK' },
      { numero: 'Volumen 15', imagenUrl: '/solo-leveling/15.jpg', precio: 28.00, estado: 'STOCK' }
    ]
  },
  {
    id: 29,
    titulo: 'SUMMERTIME RENDERING',
    autor: 'YASUKI TANAKA',
    tipoPublicacion: 'Tomos B6 con sobrecubierta',
    sinopsis: 'Shinpei Ajiro regresa a su isla natal para asistir al funeral de su hermana adoptiva, Ushio. Sin embargo, pronto descubre que hay extrañas circunstancias alrededor de su muerte y que una leyenda local sobre "sombras" duplicadas podría ser real y mortal.',
    portadaUrl: '/summertime-rendering/01.jpg',
    generos: ['Misterio', 'Sobrenatural', 'Suspenso', 'Viaje en el Tiempo'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/summertime-rendering/01.jpg', precio: 16.50, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/summertime-rendering/02.jpg', precio: 16.50, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/summertime-rendering/03.jpg', precio: 16.50, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/summertime-rendering/04.jpg', precio: 16.50, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/summertime-rendering/05.jpg', precio: 16.50, estado: 'STOCK' }
    ]
  },
  {
    id: 30,
    titulo: 'SPY × FAMILY',
    autor: 'TATSUYA ENDO',
    tipoPublicacion: 'Tomos simples con sobrecubierta e incluye páginas a color',
    sinopsis: 'El espía de élite "Twilight" debe formar una familia falsa para cumplir una misión ultrasecreta. Lo que no sabe es que la esposa que elige es una asesina profesional y la niña que adopta es una psíquica capaz de leer las mentes.',
    portadaUrl: '/spy-family/01.jpg',
    generos: ['Comedia', 'Acción', 'Espías', 'Familia'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/spy-family/01.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/spy-family/02.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/spy-family/03.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/spy-family/04.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/spy-family/05.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/spy-family/06.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/spy-family/07.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/spy-family/08.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/spy-family/09.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/spy-family/10.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/spy-family/11.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/spy-family/12.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/spy-family/13.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 14', imagenUrl: '/spy-family/14.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 15', imagenUrl: '/spy-family/15.jpg', precio: 15.00, estado: 'STOCK' },
      { numero: 'Volumen 16', imagenUrl: '/spy-family/16.jpg', precio: 15.00, estado: 'STOCK' }
    ]
  },
  {
    id: 31,
    titulo: "JOJO'S BIZARRE ADVENTURE PART VII: STEEL BALL RUN",
    autor: 'HIROHIKO ARAKI',
    tipoPublicacion: 'Tomos B6 con sobrecubierta e incluye páginas a color',
    sinopsis: 'Ambientada en una línea temporal alternativa en 1890, cuenta la historia de una épica carrera a caballo a través de los Estados Unidos. Johnny Joestar, un ex-jockey parapléjico, se une a la carrera tras conocer al misterioso Gyro Zeppeli y presenciar el poder de sus esferas de acero.',
    portadaUrl: '/sbr/01.jpg',
    generos: ['Acción', 'Aventura', 'Western', 'Sobrenatural'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/sbr/01.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/sbr/02.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/sbr/03.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/sbr/04.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/sbr/05.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/sbr/06.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/sbr/07.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/sbr/08.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/sbr/09.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/sbr/10.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/sbr/11.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/sbr/12.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/sbr/13.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 14', imagenUrl: '/sbr/14.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 15', imagenUrl: '/sbr/15.jpg', precio: 22.00, estado: 'STOCK' },
      { numero: 'Volumen 16', imagenUrl: '/sbr/16.jpg', precio: 22.00, estado: 'STOCK' }
      
    ]
  },
  {
    id: 32,
    titulo: 'TOKYO GHOUL',
    autor: 'SUI ISHIDA',
    tipoPublicacion: 'Tomos B6 con sobrecubierta e incluye páginas a color',
    sinopsis: 'En Tokio ocurren misteriosos asesinatos perpetrados por Ghouls, seres que se alimentan de carne humana. Ken Kaneki, un universitario común, sufre un accidente y recibe un trasplante de órganos de un Ghoul, convirtiéndose en un híbrido atrapado entre dos mundos.',
    portadaUrl: '/tokyo-ghoul/01.jpg',
    generos: ['Fantasía Oscura', 'Terror', 'Acción', 'Psicológico'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/tokyo-ghoul/01.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/tokyo-ghoul/02.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/tokyo-ghoul/03.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/tokyo-ghoul/04.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/tokyo-ghoul/05.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/tokyo-ghoul/06.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/tokyo-ghoul/07.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/tokyo-ghoul/08.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/tokyo-ghoul/09.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/tokyo-ghoul/10.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/tokyo-ghoul/11.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/tokyo-ghoul/12.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/tokyo-ghoul/13.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 14', imagenUrl: '/tokyo-ghoul/14.jpg', precio: 16.00, estado: 'STOCK' }
    ]
  },
  {
    id: 33,
    titulo: 'TOKYO GHOUL :RE',
    autor: 'SUI ISHIDA',
    tipoPublicacion: 'Tomos B6 con sobrecubierta e incluye páginas a color',
    sinopsis: 'Secuela de Tokyo Ghoul. Han pasado dos años desde el ataque del CCG al distrito 20. Haise Sasaki es el mentor de la escuadra especial "Quinx", humanos modificados con habilidades Ghoul. Lo que nadie sabe es que Haise oculta un pasado perdido directamente relacionado con Ken Kaneki.',
    portadaUrl: '/tokyo-ghoul-re/01.jpg',
    generos: ['Fantasía Oscura', 'Acción', 'Misterio', 'Psicológico'],
    estado: 'STOCK',
    tomos: [
      { numero: 'Volumen 1', imagenUrl: '/tokyo-ghoul-re/01.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 2', imagenUrl: '/tokyo-ghoul-re/02.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 3', imagenUrl: '/tokyo-ghoul-re/03.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 4', imagenUrl: '/tokyo-ghoul-re/04.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 5', imagenUrl: '/tokyo-ghoul-re/05.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 6', imagenUrl: '/tokyo-ghoul-re/06.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 7', imagenUrl: '/tokyo-ghoul-re/07.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 8', imagenUrl: '/tokyo-ghoul-re/08.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 9', imagenUrl: '/tokyo-ghoul-re/09.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 10', imagenUrl: '/tokyo-ghoul-re/10.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 11', imagenUrl: '/tokyo-ghoul-re/11.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 12', imagenUrl: '/tokyo-ghoul-re/12.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 13', imagenUrl: '/tokyo-ghoul-re/13.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 14', imagenUrl: '/tokyo-ghoul-re/14.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 15', imagenUrl: '/tokyo-ghoul-re/15.jpg', precio: 16.00, estado: 'STOCK' },
      { numero: 'Volumen 16', imagenUrl: '/tokyo-ghoul-re/16.jpg', precio: 16.00, estado: 'STOCK' }
    ]
  }
  ];

  private mangasSubject = new BehaviorSubject<Manga[]>(this.mangasMock);
  
  getMangas(): Observable<Manga[]> {
    return this.mangasSubject.asObservable();
  }

  getGenerosDisponibles(): string[] {
    const todosLosGeneros = this.mangasMock.flatMap(m => m.generos);
    return [...new Set(todosLosGeneros)];
  }
}